### ISSUE TITLE
Error compinit: function definition file not found

### ISSUE THREAD

**Issue by oachoor** [thomaspoignant/mac-dev-setup#24]
The script looks promising, thanks a lot!

Everything went well until the following error occurred, guess it's related to `ohmyzsh`:
```
➜  ~ source "$HOME/.zsh_profile"
/usr/local/opt/nvm/etc/bash_completion.d/nvm:87: bashcompinit: function definition file not found
/usr/local/opt/nvm/etc/bash_completion.d/nvm:88: compinit: function definition file not found
```
I've tried to define `$FPATH` but in vain, appreciate any hints.

_NB: I'm using macOS Big Sure + iTerm2_

**Comment by thomaspoignant** [comment]
Thanks for your feedback!
I did not test this script on Big Sur but maybe something goes wrong with this version.

Any chance to have the logs of your installation so I can check what's wrong here? Or can you show me what do you have in your ~/.macsetup/macsetup_profile file ?

**Comment by oachoor** [comment]
Unfortunately not 😞 

Actually I had one permission issue and I had to run this: `sudo chown -R $(whoami) /usr/local/share/zsh /usr/local/share/zsh/site-functions` in another tab in order to keep it rolling.

Other than that everything is working (except **DBeaver** which is not yet compatible with Big Sur I guess)

Here's the content of my `~/.macsetup/macsetup_profile`:
```
export PATH="/usr/local/opt/curl/bin:$PATH"
export PATH="/usr/local/opt/openssl@1.1/bin:$PATH"
export PATH="/usr/local/opt/sqlite/bin:$PATH"
if type brew &>/dev/null; then
  FPATH=/share/zsh/site-functions:
  autoload -Uz compinit
  compinit
fi
alias ls='lsd'
alias l='ls -l'
alias la='ls -a'
alias lla='ls -la'
alias lt='ls --tree'
. /usr/local/etc/profile.d/z.sh
export NVM_DIR="/Users/omarachoor/.nvm"
[ -s "/usr/local/opt/nvm/nvm.sh" ] && . "/usr/local/opt/nvm/nvm.sh"  # This loads nvm
[ -s "/usr/local/opt/nvm/etc/bash_completion.d/nvm" ] && . "/usr/local/opt/nvm/etc/bash_completion.d/nvm"  # This loads nvm bash_completion
# Go development
export GOPATH="${HOME}/.go"
export GOROOT="$(brew --prefix golang)/libexec"
export PATH="$PATH:${GOPATH}/bin:${GOROOT}/bin"
export PATH="/usr/local/opt/python/libexec/bin:$PATH"
eval "$(pyenv init -)"
export PATH="/usr/local/opt/libpq/bin:$PATH"
```

**Comment by oachoor** [comment]
@thomaspoignant it looks like it's related to `$(brew --prefix)` and `$FPATH` not being properly inserted, here: https://github.com/thomaspoignant/mac-dev-setup/blob/master/src/mac-dev-setup.sh#L46

Fixed by changing `~/.macsetup/macsetup_profile` file, to be:
```
if type brew &>/dev/null; then
  FPATH="$(brew --prefix)/share/zsh/site-functions:$FPATH"
  autoload -Uz compinit
  compinit
fi
```

Also you might have to adjust the permission/ownership for Big Sur here:
https://github.com/thomaspoignant/mac-dev-setup/blob/master/src/mac-dev-setup.sh#L42-L43
```
sudo chown -R $(whoami) /usr/local/share/zsh /usr/local/share/zsh/site-functions
chmod u+w /usr/local/share/zsh /usr/local/share/zsh/site-functions
```

**Comment by thomaspoignant** [comment]
Thanks @oachoor, I will look at that today and try to open a PR for that.
